### PR TITLE
Add I Pay You to wallets, services, and exchanges

### PR DESCRIPTION
**Pull request by MattC-IPayYou**

### CODE REVIEW

**Comment by zquestz** [comment]
So while I would love to add you to the site. We need to pick the category you are the best match for. We try not to list companies in multiple categories. Personally I think you should be under "Services". Does that work for you?

**Comment by MattC-IPayYou** [comment]
Here is the response from my CEO:

Hi Josh –

We are both a full-featured wallet that maintains all wallet functionalities but also an exchange for Bitcoin Cash with ability to purchase and sell Bitcoin Cash for USD.

Any chance we can be in “Wallet” and “Exchange” sections since we are really both?

For example, Coinbase is listed as a “Wallet” and their GDAX unit is listed as an “Exchange”.  Just like them, we are both, just sharing the same brand name.

If you need any reference on us, please feel free to reach out to Roger Ver who knows us personally.

Thanks!

Gene Kavner, CEO
https://iPayYou.io<https://ipayyou.io/>
mobile:  425.890.7989

iPayYou – The World’s Most Useful Bitcoin Wallet
LinkedIn: https://www.linkedin.com/in/genekavner
Twitter: @iPayYouWallet - https://twitter.com/iPayYouWallet
Please like us on Facebook: https://www.facebook.com/ipayyou.io/

**Comment by zquestz** [comment]
So GDAX and Coinbase are different products. Coinbase for instance could be under both Wallet and Exchange but is not, in fact many wallets now offer the ability to buy/sell crypto directly, these are still considered Wallets, and not a fully featured Exchange.

For instance is Bitcoin.com also an exchange because it has buy/sell, what about wallets with ShapeShift integration? The line is quite blurry for these products.

**Comment by MattC-IPayYou** [comment]
Hey Josh, 
I moved IPayYou to just wallets.

**Comment by zquestz** [comment]
Thanks. Will merge and cleanup the extra white space. =)

**Pull request merged**
