### PR TITLE
Animated Burger and animated mobile menu height

### PR DESCRIPTION
**Pull request by baronsferric**
Thoughts on animating the burger icon and height? Gives its a bit more polished feel.

[https://gyazo.com/f0de222df4ac9a71ce39afb1de5e3b0b](https://gyazo.com/f0de222df4ac9a71ce39afb1de5e3b0b)

### CODE REVIEW

**Comment by NxtChg** [comment]
Please, keep the animations to absolute minimum or better avoid them completely.

"Coolness" wears of quickly, but usability is there forever.

**Comment by rawb0t** [comment]
Agreed with @NxtChg.

**Comment by kenman345** [comment]
Having had to make hamburger mobile responsive menus, this can be better done to just take up the screen and cause less motion dizziness. Much cleaner if it just overlayed. moving it down means it just wasnt given the amount of time it deserves to be cleanly coded. Thats the functionality when you change the bare minimum.

**Comment by jrkong** [comment]
Lag on older devices may become an issue as well

**Comment by fyookball** [comment]
Suggestion is appreciated but most people here seem to want to keep the site simple and not merge this.  Recommend closing this PR.  Again, thank you for the suggestion!

**Comment by zquestz** [comment]
K, I am closing. It seems most users would prefer to keep it simple/functional.

**Pull request closed without merging**
