### PR TITLE
add info about upcoming protocol upgrade

### PR DESCRIPTION
**Pull request by Mengerian**
Some links and hopefully useful information to help people looking for resources to deal with the upcoming May 15th protocol upgrade.

I hand-edited the html, but I'm not familiar with working with it. I probably missed some things that need to be changed (I tried to add a new section for the announcement). It should be checked by someone who knows how to work with it.

### CODE REVIEW

**Comment by Mengerian** [comment]
Updated spec link, now that the pull request has been merged

**Comment by zquestz** [comment]
Yeah you need to add the new section to `index.html.erb`. I can review once that is changed, or I can help out and make the needed updates if you want.

**Comment by Mengerian** [comment]
OK, I added a section to index.html.erb

if you could please review it for me, that would be great :)

**Comment by zquestz** [comment]
Ok, that adds something to the nav bar, but also extends the length quite a bit. I think we can keep it off the nav for now, and just have it as the first actual section. If you want I can make the changes, let me know.

**Comment by Mengerian** [comment]
Yeah, no need to have it appear on the Nav bar.

If you could make the changes, that would probably be better. I'll likely mess something up if I try to do it, since I don't really know how the code works.

Thanks!

**Comment by zquestz** [comment]
Will get to this tonight. Thanks @Mengerian

**Pull request merged**
