### PR TITLE
Add Bitcoin-Cash-Wallet

### PR DESCRIPTION
**Pull request by wjcloud**
This SPV-Client is a fork of one of a popular android wallet, Bitcoin Wallet.
Bitcoin-Cash-Wallet uses java.

### CODE REVIEW

**Comment by wjcloud** [comment]
Also added Coinone Exchange.

**Comment by zquestz** [comment]
Bitcoin-Cash-Wallet appears to be unreleased. It also only shows 10-50 downloads so hasn't been tested by the community. Is there an open source repo for it?

As for Coinone that looks like a quality addition. Any way you can split this to 2 different PRs?

**Comment by zquestz** [comment]
Also if possible resize the images to max 60px height.

**Comment by wjcloud** [comment]
Splited two commits. You can see bitcoin-cash-wallet repo here https://github.com/bitcoincash-wallet/bitcoincash-wallet.

**Comment by wjcloud** [comment]
#15 Merged PR

**Pull request closed without merging**
