### PR TITLE
Bitcoin Cash Graphics Section

### PR DESCRIPTION
**Pull request by maplesyrupsucker**
Created easy to use graphics section with downloadable assets for logo use, merchant use, donation use, and wallet/exchange use. 

**Logos are provided in several sizes, including:**

1. Full - 2000px wide
1. Large - 1200px wide
1. Medium - 800px wide
1. Small - 400px wide
1. Vector - SVG

Merged in [BCH logos working demo ](https://github.com/bitcoincashorg/BCH-logos) built on hugo, into the templates setup by @zquestz. There's several additional css/js files added to maintain the styles as well as animations.

Will work on revising the index.html to include similar animation scroll events to maintain consistency. Having a graphics section like this will allow for easy sharing of official logos and resources and provide better consistency across web and print and can be a great resource for media and publications, and a handy asset for future merchant adoption.

### CODE REVIEW

**Comment by Mengerian** [comment]
Great addition to the site! This will be a helpful resource for the community

Thanks for the contribution maplesyrupsucker!

**Comment by zquestz** [comment]
This looks great, just a few things.

1) The header should be consistent for the new page, right now the header completely changes when we go to the Logos / Graphics section.

2) It seems the B in the logo is down a little more than the one used on the main site. I think we should make sure it is positioned slightly higher.

3) We need to add the visual scrolling effects to the home page so they are consistent between pages.

Once those are resolved then I think we are GTG! Really appreciate all your effort bringing this new page to life!

**Comment by maplesyrupsucker** [comment]
Just pushed up a major revision, which includes:

- Revised navbar
- Revised index header to match graphics section
- Merged in animations and applied to sections and items
- Modified scroll events
- Matched styles to graphics, consistent font (google fonts ubuntu font)
- Merged in navbar with sticky effects and animation toggle on mobile
- updated 16+ horizontal logos and donation/merchant assets, nudged flag down a bit so it hangs below the bottom tip of b's and a's. Unfortunately ubuntu glyphs are kind of janky, but I think it's looking a bit more natural now. 

image


The only thing I'm not sure if it's working or not is the link from Community > Graphics. Not sure if its just my local build, but may need @zquestz to take a peek to see if the href is getting users to that new section okay. It wasn't working on my end. My eyes and brain are fried though. 

If anyone is willing to help with merging and dealing with conflicts that would be hugely helpful.

**Comment by marint94** [comment]
Can we switch to the green-colored logo? Would be awesome.
BitPay, Coinbase, and major Wallets all adopted the green logo.

**Pull request merged**
