### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Zupago**

### CODE REVIEW

**Comment by zquestz** [comment]
This change does not appear to include an image.

**Comment by Zupago** [comment]
can you fix this @zquestz You’re creating a file in a project you don’t have write access to. Submitting a change will create the file in a new branch in your fork so I can upload the image

**Comment by Zupago** [comment]
please, can I know why the pull request was close thanks @zquestz

**Comment by zquestz** [comment]
You have 2 open... Same content

**Comment by zquestz** [comment]
This was a dupe

**Comment by Zupago** [comment]
oh ok due is somehow confusing the pull request, please is it ok now ??

**Pull request closed without merging**
