### PR TITLE
Add pt-PT translation

### PR DESCRIPTION
**Pull request by m4ktub**
Added Portuguese (European) translation. I've renamed the intially proposed `pt.yml` file to `pt-PT.yml` file to better coexist with #52 althout it's unclear if the translation scheme has space for language variants at this level.

### CODE REVIEW

**Comment by zquestz** [comment]
You did it perfectly! Thank you!

**Comment by rickal** [comment]
I don't understand the commentary, there is a vastly superior number of pt-BR speakers than european ones. If any single translation should be kept, there is no doubt it should be the Brazilian, which was concluded firstly than yours. So why did you uploaded yours after commenting on mine? I don't get what you want here.

**Comment by m4ktub** [comment]
@rickal I am not trying to trick you. I want both if possible and that's why I've pointed the problem in your PR and changed mine from `pt` to `pt-PT`.  What I meant by my last phrase is that we could be asked to have a single `pt.yml` due to how the YAML files are being processed. For example, Wikipedia only allows "pt". In that case none of our PR would be accepted and a new one needed to appear. But that is a moot point now as it seems `pt-BR` and `pt-PT` is acceptable.

**Comment by rickal** [comment]
There are many places where both exist, because both can be very different in wording. For high level speakers, both are perfectly readable, for common folks it can be confusing. Not sure how clear pt-BR is for portuguese, but pt-PT for some brazillians can be difficult. Just have both, as it was simply an extra language. Alternatively we could work together in a single neutral version, if that's possible.

**Pull request merged**
