### PR TITLE
Adding exchange CoinSwitch

### PR DESCRIPTION
**Pull request by SagarVimal**

### CODE REVIEW

**Comment by zquestz** [comment]
Can you please include more information about your service, including reviews from customers, and a the people behind it?

**Comment by SagarVimal** [comment]
CoinSwitch is a cryptocurrency exchange aggregator started by ex-Amazon and ex-Zynga engineers. It has integrated many leading exchanges to provide best exchange rates and a comprehensive list of cryptocurrencies to its customers for exchange. Now traders don't have to visit multiple exchanges to exchange their coins. You can find customers reviews here: https://www.trustpilot.com/review/coinswitch.co

**Comment by SagarVimal** [comment]
Please let me know if you need any other information from my side.

**Comment by zquestz** [comment]
I am hesitant to add your service. The link you provided does not seem to have legitimate reviews. All the reviewers have never reviewed another product. In addition, when searching Google for "coinswitch reviews", it returns some rather unfavorable results.

Do you have any reviews from people that have a history? I like to qualify any service before putting it up on the site.

**Comment by SagarVimal** [comment]
Thanks for your reply @zquestz. We are quite a new service. We started our operations 6 months back. So we don't have many reviews. But I can share a couple of more review here: 

- https://www.scambitcoin.com/coinswitch/ 

- https://steemit.com/cryptocurrency/@jaichai/coinswitch-solving-major-hassles-plaguing-cryptocurrency-traders

We are supporting BCC from the week it's listed on exchanges for trading. Even you can google "How to buy BCC" and you will get our content on top.

**Comment by zquestz** [comment]
Unfortunately due to lack of information about your service I am going to take the advice from the article you linked.

"...given that it’s been launched only recently, the best course of action is the one suggested at the end of the bitcointalk thread, which is to wait it out and see."

When you become more established feel free to reach out again. I will also proactively add the site if I see positive momentum and support within the community.

**Comment by SagarVimal** [comment]
Thanks for your reply. The article has also written that the service is legitimate. The unfavorable reviews which we have received are from users who have received fewer coins than expected and this is possible because of delay in blockchain confirmations and price fluctuations. This happens on Changelly and ShapeShift as well. 

Coins like NEO, PIVX has added us as an exchange. CoinSwitch is a legitimate service. You can try it by yourself. I hope you can understand my points.

**Comment by zquestz** [comment]
Well that wasn't the only occurrence I found. http://bittrust.org/coinswitch/0

**Comment by SagarVimal** [comment]
I got one more review of CoinSwitch: https://bitcoinexchangeguide.com/coinswitch/

Regarding Bittrust: The complaint about getting fewer coins will be there and we openly mention this on our platform that the quantity of coin you receive may vary with what you see during the comparison. We are not the only one who is getting that sort of reviews. This will be there for every service which is working on that way. You can see one here http://bittrust.org/shapeshift

I think we should close this loop here. CoinSwitch is my company and I can say that it is legitimate. Thanks a lot for all your replies and time. :)

**Pull request closed without merging**
