### PR TITLE
Update ticker to BCH

### PR DESCRIPTION
**Pull request by zquestz**
This is now up for community review. The goals of moving to BCH:

1) Have a consistent ticker for all exchanges and wallets.
2) Remove confusion around Bitconnect which also uses BCC.
3) Work with the industry which has already begun adopting BCH.

Please provide your feedback.

### CODE REVIEW

**Comment by fyookball** [comment]
I see no reason not to do this.  Initially , we said 'lets let the market decide'.  It has.
No point to battle the ticker with bitconnect, which will be around for who knows how long.
Most exchanges use BCH.  Pointless to say something different on our site.

**Comment by NxtChg** [comment]
> Have a consistent ticker for all exchanges and wallets.

Yeah, BCC.

> Remove confusion around Bitconnect which also uses BCC.

Why do we have to help a scam-coin survive?

> Work with the industry which has already adopted BCH.

Can you clarify this statement? What "industry"? Is there any actual data?

**Comment by NxtChg** [comment]
> Most exchanges use BCH.

Exchanges do not define the ecosystem. Bitcoin Cash is very young, too soon to proclaim this settled.

**Comment by fyookball** [comment]
@NxtChg it doesn't matter if its a scam.  It's well marketed and its a top 10 coin.  Hoping its going to go away is not a strategy.

**Comment by NxtChg** [comment]
> It's well marketed and its a top 10 coin.

It only activated after Bitcoin Cash started using BCC.

**Comment by zquestz** [comment]
@NxtChg yeah, if you look at the list of exchanges and wallets, many of them are already using BCH. I agree there are quite a few that also use BCC but right now it is very even, and one is already in use. Also the highest volume exchange (HitBTC) is already moving to BCH.

That being said, I am open to discussion and want to make sure the community is ok with this change.

**Comment by fyookball** [comment]
that may be true @NxtChg but the network effect of widespread BCH usage is already here.

**Comment by coinstash** [comment]
Worst case of Cranio-Rectal inversion I've ever seen. How do you justify XBC then? "Oh, but Bitcoin Plus has only been around since ... err, 2014."

Fucktard.

**Comment by NxtChg** [comment]
@zquestz by not resisting the change and giving up too early, just because of a few exchanges, we make it a self-fulfilling prophecy.

**Comment by Bitcoin-2** [comment]
Eventually, we'll go back to using BTC. While we wait for Segwit to die, we should use BCH. We need to avoid confusion with the scam coin, Bitconnect.

**Comment by NxtChg** [comment]
> Eventually, we'll go back to using BTC. 

That's the spirit :)

**Comment by zquestz** [comment]
Would love to keep the conversation constructive. Honestly I like BCC and think it is a good ticker, but am not happy about the confusion. I have been asked on multiple occasions about it and just want to make sure we are doing the right thing.

No decision has been made, this is merely to discuss it.

**Comment by zquestz** [comment]
Additional data point. More volume and exchanges use BCH than BCC. https://coinmarketcap.com/currencies/bitcoin-cash/#markets

**Comment by rawb0t** [comment]
BCH is good. Plus it lets us use those nice BCH PLS shirts

**Comment by memalley** [comment]
main reason to use BCH is for the "BCH PLEASE" t-shirts... only half-kidding. 
HAHA! Just saw comment above said same thing, lol, promise I didn't read beforehand. 

Seriously though:

- majority of exchanges are using BCH

- BCC, like it or not, is already taken

- we need unity more than this or that ticker. momentum is weighted on bch side. 

I say we make plans for BCH and if/when bitocincash.org makes BCH official we flip the switch

**Comment by dgenr8** [comment]
ACK

**Comment by howelzy** [comment]
Paybacks a BCH...

**Comment by jesseposner** [comment]
ACK

**Comment by Greg-Griffith** [comment]
ACK

**Comment by xjamesb** [comment]
I am a Bitcoin novice and use the Trezor hardware wallet. This uses BCH for Bitcoin Cash so I think that Trezor users would be in favour of this ticker.

**Pull request merged**
