### PR TITLE
Added full Spanish translation.

### PR DESCRIPTION
**Pull request by ealmansi**
Added full Spanish translation.

Not an automatic Google translation. I tried to keep it 100% neutral Spanish. Peer review from other Spanish speakers is welcome.

### CODE REVIEW

**Comment by zquestz** [comment]
Seems another user also submitted spanish. Do you mind double checking the merged es.yml and making suggestions/improvements?

**Comment by ealmansi** [comment]
I've read @gabe1986 's later version. It seems generally acceptable, although I do see a few issues with the merged translation. I mention these below.

I've also improved the version in this PR based on the merged one. 

----------

Wrong/missing translations:
- "depósito de valor" is not the same as "store of value". A more accurate translation is "reserva de valor".
- "dinero sonante" is incomplete (the correct expression is "dinero contante y sonante"), and it effectively means "cash", not "sound money". A more accurate translation is [moneda fuerte](https://es.wikipedia.org/wiki/Moneda_fuerte).
- "Exchange" translates into [Casa de cambio](https://es.wikipedia.org/wiki/Casa_de_cambio).
- "Wallet" (when talking specifically about cryptocurrencies) translates into [Monedero](https://bitcoin.org/es/elige-tu-monedero).
- DAA should use the Spanish acronym AAD.

Small errors:
- Spurious space characters: L89
- Typo: "icrementó" L225
- Grammar: "Cualquiera que tuviera (...) se vuelve (...)", "el incremento igualaría bloques"

Also the tone seems overly informal at times:
- "corre" instead of "funcionar"
- "mandar [dinero]" instead of "envíar"
- "se dispararon por los cielos"

**Comment by zquestz** [comment]
Thank you for proof reading, I really appreciate it. Your changes look great. I am going to merge and resolve the conflicts for you.

**Comment by ealmansi** [comment]
Great, thanks. A professional translator has reached out to me via email and might be sending suggestions for further improvements. I'll submit another PR in that case.

@gabe1986 If you find any issues with the latest version, please do bring them up.

**Pull request merged**
