### PR TITLE
Add ZuPago 

### PR DESCRIPTION
**Pull request by Zupago**
zupago

### CODE REVIEW

**Comment by zquestz** [comment]
Couple of notes on this. Seems your main product is the wallet, and we don't like putting duplicate logos in. If you can only include the wallet that would be ideal. Your services are not the main offering and are merely accents to the wallet you provide.

Second do you have a place with user reviews and testimonials? I have searched the internet for information about ZuPay and all I can find is promotional material from your team. I would love to see user feedback before I add it to the site.

**Comment by Zupago** [comment]
check 
https://chrome.google.com/webstore/detail/zupago-bitcoin-btcbch-tra/mnalladdhdlgjmjoocjnoolbehpkmhhp

https://www.trustpilot.com/search?query=zupago

**Comment by Zupago** [comment]
Seems your main product is the wallet YES

**Comment by fyookball** [comment]
Respectfully declining (for now) due to lack of reputation/transparency.

**Comment by Zupago** [comment]
really funny noted

**Pull request closed without merging**
