### PR TITLE
Added Freewallet.org wallet

### PR DESCRIPTION
**Pull request by freewallet**

### CODE REVIEW

**Comment by OverlordQ** [comment]
I don't think promoting custodial wallets is in the benefit of the community.

**Comment by freewallet** [comment]
Let's be honest: a lot of people use custodian wallets (like Freewallet or Coinbase) because what we offer isn't just a wallet. We offer an exchange as well, commission-free transactions and flash transfers between accounts. Users consider a lot of factors before choosing a custodian wallet. Some people are convenience driven. Cryptos make you take the responsibility for own finances.  We appreciate it, but it's not for everyone!

**Comment by zquestz** [comment]
I have seen far too many complaints about this wallet to add it in good faith. I would need other people to vouch for this to be added. This is not something I am willing to endorse.

**Comment by freewallet** [comment]
Any live service on a highly volatile cryptomarket can expect to face issues eventually. Google any wallet/exchange/trading platform name, and you'll find lots of negative comments: people tend to blame the service provider if something goes not as they expected. At Freewallet, we follow up on all complaints from our users and work on resolving their issues. We also have proven records of numerous successful support cases including large BCH refunds as well. 

Can you recommend someone we can discuss the opportunity to be listed on BitcoinCash.org with further?

**Comment by fyookball** [comment]
Far too complaints about this wallet.

**Pull request closed without merging**
