### PR TITLE
Create <ko>.yml

### PR DESCRIPTION
**Pull request by GinkgotreeKr**

### CODE REVIEW

**Comment by zquestz** [comment]
This appears to be a duplicate of your other PR with a slightly different file name. Closing. Feel free to open if there are additional changes needed.

**Comment by GinkgotreeKr** [comment]
Hi Josh.
I am not good at Github.
If I want to modify, what should I do?

**Comment by zquestz** [comment]
If you want to modify feel free to just post a gist in the issues section. You can create them at gist.github.com =)

**Comment by GinkgotreeKr** [comment]
I sent a modification at gist.github.com.
Thanks. :-)

2017-12-17 19:20 GMT+09:00 Josh Ellithorpe <notifications@github.com>:

**Comment by GinkgotreeKr** [comment]
Just before I saw bitcoincash.org site.
And there is previous ko.yml.
Yesterday I sent modified file on gist. (private?)
I need to send it again?

Greetings.

2017-12-17 19:20 GMT+09:00 Josh Ellithorpe <notifications@github.com>:

**Comment by GinkgotreeKr** [comment]
https://gist.github.com/GinkgotreeKr/225655c0e60da1de3c0c71011b7b589f

I modified ko.yml file.
Pls apply this file.

Thanks. :-)

2017-12-17 19:20 GMT+09:00 Josh Ellithorpe <notifications@github.com>:

**Comment by zquestz** [comment]
Really late here, promise I will get to this soon. =)

**Comment by zquestz** [comment]
This has been posted!

**Pull request closed without merging**
