### PR TITLE
Started the list of merchants.

### PR DESCRIPTION
**Pull request by josephcastan**
Made it a separate file because it will eventually grow big.

Should probably wait until we have more merchants there before linking to it from the home page.

Suggest merchants and I will add them to the list.

### CODE REVIEW

**Comment by NxtChg** [comment]
example

**Comment by zan56** [comment]
https://www.etsy.com/shop/CerberusBoutique

**Comment by NxtChg** [comment]
@zan56 I don't see Bitcoin Cash as a payment option anywhere. Does Etsy accept Bitcoin Cash?

**Comment by zan56** [comment]
Etsy itself doesn't take BCH but the seller does and ends up paying Etsy a monthly seller Fee instead. We had a full conversation on the top. See here https://www.reddit.com/r/Bitcoincash/comments/7d35u8/added_bch_as_a_payment_method_in_my_etsy_shop/

**Comment by zan56** [comment]
https://kawaiicrypto.com/

**Comment by NxtChg** [comment]
> Etsy itself doesn't take BCH but the seller does and ends up paying Etsy a monthly seller Fee instead. 

This is confusing to users. They will follow links from the list expecting to be able to pay with Bitcoin Cash and it's far from obvious how. Let's instead petition Etsy to add official Bitcoin Cash option.

> https://kawaiicrypto.com/

Right now the site is down, I will check it later again.

@zquestz Can you merge this please, so I could start adding more merchants to the list? Not very familiar with GitHub, so don't know how to add to PRs.

**Comment by zquestz** [comment]
To add to PR's all you have to do is keep updating your branch with new content and push it. Github automatically updates the PR for you. =)

**Comment by NxtChg** [comment]
@zquestz Thanks for the tip, gonna try it - need to add AirVPN anyway.

**Comment by NxtChg** [comment]
Huh, looks like the magic worked :)

**Comment by zan56** [comment]
https://fudmartng.com/

**Comment by geliyoo** [comment]
Can we add Xtremcoin to the Bitcoin Cash page? Bitcoin offers cash deposit and exchange service. With Bitgo Instant Service.
https://www.xtremcoin.com

**Comment by NxtChg** [comment]
@geliyoo a) this is not a merchant so it goes into some other section, b) I don't see any mention of Bitcoin Cash.

**Comment by zquestz** [comment]
Even though they are using ShapeShift, I think that OverStock should be added to the list.

**Comment by NxtChg** [comment]
@zquestz Added, but are you sure they accept Bitcoin Cash? I couldn't find anything about Bitcoin Cash in their help section, people might get confused...

**Comment by zquestz** [comment]
They do, they use ShapeShift to accept any form of crypto. They then get paid in Bitcoin. Hopefully they add native support soon, but for now they are still the biggest retailer that takes Bitcoin Cash, even if the conversion rate is less than ideal.

**Comment by NxtChg** [comment]
Maybe we should merge this? It would encourage people to submit more projects.

**Comment by bitcoincashstickers** [comment]
http://bitcoincashstickers.com/

**Comment by cala99** [comment]
www.instasmarter.com accepts Bitcoin, Bitcoin Cash, Litecoin and other cryptocurrency. It is a Top social media followers and likes provider Available on Instagram, Facebook, Twitter, YouTube, SoundCloud, Pinterest, LinkedIn, etc Price starts at 1.49 USD only

**Comment by schancel** [comment]
Hello,

Thank you for your contribution.

We are migrating to a combined repository to improve the website experience.  This includes:

* Adding a developer portal, which includes protocol specification, and other resources
* Switching to a common template rendering sysmte ([Jekyll](https://jekyllrb.com/))
* Automated deployments to a staging area to facilitate in interative development.

Please help us by submitting your pull request to the new repository:

http://github.com/bitcoincashorg/bitcoincash.org

**Pull request closed without merging**
