### PR TITLE
Added Coinbase to Exchanges

### PR DESCRIPTION
**Pull request by nishantsharma87**
https://blog.coinbase.com/buy-sell-send-and-receive-bitcoin-cash-on-coinbase-65f1b2c7214b

### CODE REVIEW

**Comment by zquestz** [comment]
So  currently we have GDAX in Exchanges, and Coinbase listed in Wallets (I know not ideal). Reality is that Coinbase is a brokerage, not quite an Exchange. How do others feel about the current placement?

**Comment by nishantsharma87** [comment]
Ah! Thanks for the info. I didn't notice that. Would it be a better idea to have Coinbase listed there instead of GDAX just because Coinbase is more popularly known and more easily verifiable by a simple Google/Wikipedia search ? The link could still direct to GDAX. What do you think ?

**Comment by Egon01** [comment]
Put Coinbase in both sections... the more the merrier ;)

**Comment by zquestz** [comment]
Going to leave this in Wallets for now.

**Pull request closed without merging**
