### PR TITLE
add ALFAcashier.com to the exchange list on bitcoincash.org website

### PR DESCRIPTION
**Pull request by ALFAcashier**
We've modified all urls to the bitcoincash. Sorry for that. Here is a new pull request.

Thank you.

### CODE REVIEW

**Comment by zquestz** [comment]
Thanks for making the change. Really appreciate it. =)

**Comment by ALFAcashier** [comment]
Hi. Is there any ETA on the merge?

Thanks.

**Comment by zquestz** [comment]
Will be doing it tonight. At work atm.

**Comment by ALFAcashier** [comment]
Thanks a lot!

**Pull request merged**
