### PR TITLE
Added Service: Pastecoin.com

### PR DESCRIPTION
**Pull request by Nawsen**
#86

### CODE REVIEW

**Comment by zquestz** [comment]
I do not see BCH support on this website. It only mentions BTC.

**Comment by bcashier** [comment]
@zquestz  You can sell with USD / BTC , but when someone want buy, the website convert automatically the price to BCH.

Try any product and you see that you can pay for it with BCH.

They announced the adding here: https://twitter.com/PasteCoin/status/943562876513673216

**Comment by zquestz** [comment]
How does the poster receive payment? Do they get that directly in BCH or is it converted to BTC and therefore requires high fees?

**Comment by schancel** [comment]
Hello,

Thank you for your contribution.

We are migrating to a combined repository to improve the website experience.  This includes:

* Adding a developer portal, which includes protocol specification, and other resources
* Switching to a common template rendering sysmte ([Jekyll](https://jekyllrb.com/))
* Automated deployments to a staging area to facilitate in interative development.

Please help us by submitting your pull request to the new repository:

http://github.com/bitcoincashorg/bitcoincash.org

**Pull request closed without merging**
