### PR TITLE
Redesign proposal

### PR DESCRIPTION
**Pull request by t4t5**
After the SegWit2x fiasco, I want to do as much as I can to help Bitcoin Cash succeed.

As a designer and frontend-developer, I thought that my best contribution would be to redesign the bitcoincash.org website:

screenshot

I've already coded the gist of it and uploaded it to one of my spare domains: [TRY THE DEMO](http://wingle.me)

I realise that this is a big change from the current structure, but in my opinion it's worth it. :)

- Cleaner, more extensible design
- Easier to contribute to (most data is simply stored in markdown files)
- Uses a modern development environment ([Gatsby](https://www.gatsbyjs.org/) + React.js)

Instructions for running it locally are in the README-file. I'm currently using GitHub Pages to host the site, but it should be simple to use in a Docket setup as well.

Let me know what you think!

/Tristan

### CODE REVIEW

**Comment by deadalnix** [comment]
Repeating what has been said. This change the branding completely so this is a non starter. Being recognized is by far more important than being pretty. Any redesign needs to keep the branding.

**Comment by fyookball** [comment]
I second what @deadalnix is saying.  I am against changing the logo.  BitcoinCash.org should keep orange logo as is.  That being said, I like the general design sense.

**Comment by CryptoKidd** [comment]
This is really well done.  The simplicity stands out for me. Easy to access the wallet and exchanges tabs, with clean easily distinguishable options. 

Regarding branding; I feel consistency will be important moving forward as more potential Bitcoin forks enter and confuse the market. Though this will be an important topic with deeper levels. Green does identify well- and I’ve been using it in most of my videos/ social media work.

Either way- thanks for your time, awesome job.  I’ll be doing what I can to create videos and ads to share the info on Bitcoin Cash. Feel free to reach out- Peace.

**Comment by Kakifrucht** [comment]
I am really liking this redesign. Very easy, simple, clean. 
I also welcome the color change. Bitcoin hasn't reached mainstream adoption yet, and Bitcoin Cash is shooting for it. Orange is not yet connotated by the general public to be the color of Bitcoin, and green has some very positive marketing effects to many people in itself ("did you know that Bitcoin Cash is greener than Bitcoin Core?").

Could you however try to align the Bitcoin in the animation to move centered on the dashed lines?

**Comment by monsterbitar** [comment]
The sticky menu when scrolled puts white text against white background.

**Comment by monsterbitar** [comment]
Overall I feel it's a significant upgrade, please spend the extra time to adapt it according the requirements (change colors to match branding,tilt the B the right way etc)

There is also a missing ticker that I feel should be returned.

**Comment by ftrader** [comment]
I like the design, if some way could be found to make the brand stand out a bit more that would be awesome. I think the branding gets lost a bit, it's quite subdued.
But the arrangement of the information and the presentation is an improvement for me.

No doubt you've already put substantial effort in - thank you for this.

**Comment by paOol** [comment]
some feedback:

visually its an improvement.
UI/UX-wise, I think people are more likely to quickly scan and scroll through the page and bounce in under 4 seconds, compared to the existing page.

The additional pages are hidden behind navigation menus. A significant portion of people will not click through those menus and leave the site.

I personally don't have an issue with the color/branding choice. I think there should be diversity (orange, green, and i'd even argue for blue as well). 

If the changes are not accepted, I'd suggest you simply create this site independent of the bitcoincash.org website. Obviously choose a different domain and modify the content a bit so there is at least some original content on the new site.

Also , might I suggest adding this faucet site somewhere

https://learnbitcoin.cash/faucet

**Comment by NxtChg** [comment]
Nice redesign. Scrolling is way more responsive too.

About branding: it's stupid to try and mimic Bitcoin with its orange color. Only adds confusion.

It's _way_ better to have our own green branding, which is calm, respectful, associated with money and makes it stand out.

P.S. If bitcoincash.org rejects it, start your own version at a different domain. This should not go to waste.

**Comment by NxtChg** [comment]
> I like the design, if some way could be found to make the brand stand out a bit more that would be awesome. 

Yep, the design is currently a bit "bland". Would be nice to liven it a bit.

**Comment by moonkin48** [comment]
@t4t5, to echo @NxtChg, if this pull is rejected (and I understand the rationale for it being rejected), I encourage you to continue with your work and publish to a different domain. 

There is no official Bitcoin Cash website. There is however the _best_ (visually and functionality) Bitcoin Cash website, which will in time become the most popular.

Consistent branding has value. But who decides the branding for Bitcoin Cash? No one. So branding will organically emerge and evolve over time.

**Comment by schancel** [comment]
@t4t5 This looks great.  Thank you for your hard work.

**Comment by fyookball** [comment]
@t4t5 I suggest try to submit again with the original bitcoincash.org branding ...it would have a much better chance to be adopted on bitcoincash.org

**Comment by deadalnix** [comment]
Agreed with @fyookball . This design definitively looks good. I'd be all for going with it if it can be modified in order to adopt the proper logo and other branding elements.

**Comment by t4t5** [comment]
@fyookball @deadalnix I'll work on an updated version!

**Comment by zquestz** [comment]
Just wanted to say I really love the design. Thanks for putting in the effort to do this. Looking forward to seeing an updated version in orange, since it seems many here are focused on keeping the logo as is.

As for the green/orange debate, I am not partial to either color, but I do believe we need to use a circular logo, and to meet that requirement and still have brand recognition I think green works better for that use case..

There are a few reasons for this, and I have given it a lot of thought.

1) Rectangular logos are a no-go for me. They don't fit in many designs, and makes the overall logo smaller in many layouts since it can't fit in a square frame. This can be clearly seen in every multi currency wallet, and a number of exchanges.

2) I really like the Bitcoin symbol in the logo, and since I want to move to a circular design and don't want to change the symbol, then the most obvious choice is to change the color. I believe that gives it more distinction than just rotating it upwards.

3) The market currently recognizes BOTH logos. So many people have used the green, that both the green and orange are recognizable right now. Therefore if we are going to make a change, now is far better than later.

4) Green is the color of the world reserve currency, and many recognize cash as green.

Now, I agree that being recognized is a key element for a logo, it also has to look good on websites, exchanges, wallets. Pretty much every crypto currency uses a circular logo, or at bare minimum a logo that fits in a square frame. I think departing from that design is a mistake, and one that can still be corrected.

**Comment by cranau** [comment]
I agree with @zquestz on round green logo. It will fit nicely a square aspect ratio format and it differentiates from Legacy Bitcoin. The green feels modern and is well recognized in the community.

**Comment by Kakifrucht** [comment]
@deadalnix could we open this up for debate?
Does Bitcoin Cash want to be Bitcoin? It is already, but is it really necessary to adopt 90% of it's branding? I think this is the perfect time to rebrand. There seem to be many people who would like to hold on to the "refresh" aspect of it.

I personally completely agree with @zquestz thoughts.

**Comment by fyookball** [comment]
@Kakifrucht  @zquestz   I like the rectangle.  I think its distinctive, aesthetic, and already a brand/meme.

**Comment by NxtChg** [comment]
People say that the green color will add confusion, but I think the reverse is actually true - the more similar we look to the Legacy Bitcoin, the more people will send money to the wrong chain or do some other mistake, simply because they will fail to catch the distinction.

Legacy and Cash are two different entities now (until Legacy dies), so they should look distinct. And when the legacy dies, it might still be a good idea to keep the modern design and treat it as a re-branding of old, bad Bitcoin - to distance ourselves from Core's damage. Green is also calm, respectful, trustworthy and associated with money.

It also doesn't help if we are perceived as some sort of a copycat of Bitcoin.

As for the round design. I think the added rectangle is great: it adds distinction and the logo looks like a bill. To fit it into square slots you can easily crop the rectangle at any length.

**Comment by t4t5** [comment]
@zquestz & @NxtChg I had pretty much the exact same thought process as you guys. Thank you for putting it into words!

@fyookball and @deadalnix seem to think that we don't care about, or don't understand, branding. I'd argue the opposite – I'm endorsing the green precisely *because of* branding. Looks *do* matter in a brand, and it's wroth remembering that Bitcoin itself went through quite a few iterations before the community settled on a well-designed logo.

Let's imagine that Coinbase were to adopt Bitcoin Cash in the near future. This is what their wallet UI currently looks like:

1461b288-427f-483a-8489-39eef52eda90

How do you expect them to distinguish Bitcoin from Bitcoin Cash in their icons with the current logo? Honestly, I can't really come up with any good suggestions. 

With a green color on the other hand, the answer is simple: 

screen shot 2017-11-11 at 11 55 59

**Comment by NxtChg** [comment]
To illustrate that it's not unreasonable to use the bill logo in a rectangular slot:

example

Although in this particular case it's probably better to use the round one, bun in general there is no reason why we can't use both depending on the best fit.

**Comment by t4t5** [comment]
@NxtChg Anything is possible, but I can almost guarantee that Coinbase's UI designer will refuse to implement that design. It looks like a bug. :)

**Comment by NxtChg** [comment]
@t4t5 In that particular case I absolutely agree. But when not all icons are round, you can still fit the bill logo into a square slot:

example2

**Comment by NxtChg** [comment]
Example of a recent post in /r/btc:

example3

This kind of branding would not work with both colors being orange.

**Comment by t4t5** [comment]
I've redesigned the website to use the existing branding elements now:

screen shot 2017-11-11 at 14 56 55

Although I still have a slight preference for the green theme, I think this one turned out really well as well. :)

[LIVE DEMO](http://wingle.me/)

**Comment by NxtChg** [comment]
@t4t5 awful! You broke the consistency of design with this quick hack and also so much of the nasty orange is hurting my eyes...

**Comment by t4t5** [comment]
@NxtChg Seems like pleasing everyone will be an impossible task...

**Comment by NxtChg** [comment]
@t4t5 You don't have to please everyone. You made a great and consistent design. If bitcoincash.org is too pig-headed to accept it - let's make another site with that design. I wanted to make a good Bitcoin Cash directory anyway.

People will continue using two colors and there is no changing it. In the end the most adopted will win.

**Comment by deadalnix** [comment]
Thanks for moving this forward. For the 'Bitcoin Cash' near the logo, no italic and capital B, capital C.

There is probably some work that needs to be done on the color palette, as the green bar on top with the orange themed site is quite aggressive. But I trust this is not the final iteration and @t4t5 wanted quick feedback on the direction this si going and it ertainly doesn't deserve to be qualified of "awful" or "nasty".

@everybody Please do not let this thread degenerate into the high noise and low signal place. Everybody has its preference when it comes to design but keep in mind that matching anyone's preference is not the goal here. To put it bluntly, pretty nobody commenting here is the target audience of this website so your preference are irrelevant. Let's provide @t4t5 with high quality feedback so his design can converge quickly toward something that can be merged, as this is what's in the best interest of the coin.

Regardless of what you think of the branding, this is really out of the scope of this change so the discussion about it here is unlikely to lead anywhere productive. If someone feels like a rebranding is required then here is what i suggest:
 - Make a strong case why the current branding doesn't do it's job. Chaining these things is expensive, so the flaw needs to be serious. `Could be better` is just not enough here.
 - Provide a strong alternative. Using the same logo as bitcoin and paint it green is not a strong alternative.

In any case, this discussion needs to take place elsewhere.

**Comment by NxtChg** [comment]
@deadalnix Nobody talks about _personal preferences_ here. There were arguments given for better branding, but you can't hear them over your own arrogance, as always.

**Comment by Kakifrucht** [comment]
Really, you are going to call the feedback given noise? Have you even read the previous comments?

@NxtChg being insulting is probably not the right approach either.

**Comment by NxtChg** [comment]
@Kakifrucht I am not trying to insult, but sometimes people need honest feedback to sober up a bit.

**Comment by deadalnix** [comment]
@NxtChg I'm not sure what you are doing here if you think we are pig headed and arrogant, and this design is awful and nasty. I'm sorry you are not happy with us and more specifically me, but that's the way it is.

@Kakifrucht I hear that people have other preferences in term of branding. I hear that some branding elements could be improved. It's all well and good, but we are here trying to get @t4t5 's design in a shape where it can be put live. The shortest path toward that is to fit into existing branding. The alternative path is to recreate a new branding. this is a much bigger task than the design change only. While this isn't a task I think is worth it, I'm not an idiot and can be convinced. On the other hand, @t4t5 has put work into this, I think this is good work, and I see no reason to not use that work because some people are not happy with the current branding. This is mostly off topic, so yes, no matter how informative it is about branding, that is not helping @t4t5 getting shit done, which is what this PR is about.

**Comment by Kakifrucht** [comment]
@deadalnix You have some points, but at the same time you are treating the green branding as something completely new. It wasn't just invented by @t4t5 in his original proposal. Even [Roger spread the green version](https://www.reddit.com/r/btc/comments/70npfi/a_bunch_of_fantastic_bitcoin_cash_logos_and/) recently and especially in r/btc I see it getting used over and over again. We all know that bitcoincash.org will have a big influence on which branding gets adopted, which is why in my opinion it shouldn't just be discarded immediately. Green comes with many advantages that were already pointed out.

**Comment by NxtChg** [comment]
@deadalnix I already left your ABC repo and not gonna contribute anything to it, you kicked out zander, you either don't read half of what's written here or just organically can't listen.

You put words into my mouth, I didn't say this design is awful and nasty. I said that the last quick hack is awful and the orange color is nasty, but you either don't bother to read or is not below twisting people's words in an attempt to discredit what they are saying and enforce your idea of how things should be. Nice Core tactics there.

Keep alienating people and soon you will find yourself sitting all alone on your wonderful throne.

**Comment by NxtChg** [comment]
Another example, this time from twitter, which again cannot be used without color distinction:

example4

**Comment by fyookball** [comment]
personally, I like the green.  I just dont like changing the flag.

**Comment by monsterbitar** [comment]
I personally prefer the green. Please do go ahead with that if you prefer to :)

**Comment by fyookball** [comment]
@monsterbitar maybe we have both orange and green flags

**Comment by fyookball** [comment]
Orange on white bg, not white on orange bg!  This looks MUCH different than simply green on white.

**Comment by zquestz** [comment]
@t4t5 I think we should continue iterating on your new design. I really like it a lot. I think we can make the orange one work better if we remove the green accents. The orange/green mix just doesn't work for me. I can help provide assets, or help if you need any assistance.

Really appreciate all the hard work, lets take this over the finish line. =)

**Comment by BigBlockIfTrue** [comment]
Regarding orange versus green, I saw one website using round logos both Bitcoin and Bitcoin Cash used a darker shade of orange for Bitcoin Cash (in addition to the backward tilting). This might also be a practical solution when round logos must be used.

You now coloured your entire design orange. What if you keep the green design, but use an [orange logo](https://www.bitcoincash.org/img/logo-dark.png)? Similar to above, you could adjust the shade of orange to make it fit better in the design. You could also try blue instead of green, that might go even better along with orange. Also, to emphasise Bitcoin Cash as a brand, I'd suggest keeping a [large logo](https://www.bitcoincash.org/img/bitcoincash-white.png) on the top of the homepage.

**Comment by NxtChg** [comment]
People who argue in favor of orange design don't understand how branding works and should go read up on the topic if they want to make any sort of informed decision.

The ultimate goal of branding is to carve up some space inside user's mind. You do this by standing out, by being unique. Color provides immediate subconscious recognition. When both things are orange, your brain needs to stop and pass control to the higher levels, which will have to spend some mental energy thinking "ok, which one is which again?".

If Pepsi used the same colors and similar logo to Coca-Cola, do you think it would be perceived as a worthy competitor or a cheap knock-off? In many countries local producers often release soft drinks that mimic Coca-Cola and nobody ever remembers their names or has any respect for them. They don't think "or this is also red and curvy, it _must_ be as good as Coca-Cola".

The word is full of Fony and Panafonics, let's not be.

**Comment by NxtChg** [comment]
This is an example of how you do branding, of how, through posts like these, you gradually carve up a space for yourself in user's mind:

example

Other examples I posted above.

**Comment by xjflyes** [comment]
I made a poll about the color preference in BCH 100 Club.
Until now, 45 people voted. 93.3% prefer green. 
For reference only.

**Comment by Egon01** [comment]
I favor orange. Why? When Bitcoin Cash becomes Bitcoin (most secure chain, the longest chain with the most PoW etc.), are we gonna switch back from green to orange. 

If we go with green, we are manifesting the disconnection to bitcoin and cause more confusion.

**Comment by NxtChg** [comment]
>  When Bitcoin Cash becomes Bitcoin 

Sorry, no matter how much we all would like to take Bitcoin's brand it's not gonna happen, no more than Pepsi can take Coca-cola's brand by adding a bit of sugar to its product. Heck, even Coca-cola couldn't do it to _their own brand!_

This is not how it works. Bitcoin and Bitcoin Cash are two different things, end of story.

We can either be a copycat or "next and improved", in which case we need a unique, distinguishing brand: modern, hip, fresh.

Unique branding also helps us present Bitcoin Cash as a "new thing", which is always good, and distance ourselves from all the damage that Core did.

**Comment by Egon01** [comment]
>Sorry, no matter how much we all would like to take Bitcoin's brand it's not gonna happen, no more than Pepsi can take Coca-cola's brand by adding a bit of sugar to its product. Heck, even Coca-cola couldn't do it to their own brand!

I disagree politely. 

Bitcoin is not a trademark like Pepsi or Coca-Cola that can be legally enforced. The most secure chain that shares the Bitcoin genesis blocks defines Bitcoin (see white paper). Currently, legacy bitcoin has this privilege. But as soon this shifts towards Bitcoin Cash, Bitcoin Cash is a rightful successor. Bitcoin Cash restores Bitcoin.

**Comment by NxtChg** [comment]
> I disagree politely.

And I politely ask you to read up about how branding works :)

I was not talking about trademarks, I was talking about user's brain.

No amount of your rational reasoning ("longest chain, blah-blah-blah") will have any effect here.

[New Coke](https://en.wikipedia.org/wiki/New_Coke) had _objectively_ better taste, didn't help at all.

**Comment by NxtChg** [comment]
By the way, Bitcoin Cash has pretty much the same problem as New Coke, but we have one crucial advantage - the word "bitcoin" became a commonplace word. For regular people it collectively describes "those weird digital moneys", almost synonym with "cryptocurrency".

So if we can re-brand old Bitcoin to Bitcoin Core, then we can create a new "baseline". It's like buying a Canon xerox machine - you don't think about Xerox as a trademark anymore. Or using DuckDuckGo to google something.

**Comment by rickal** [comment]
I think the green works, but it all depends on what is the future of bitcoin. I have no doubt BCH is bitcoin, BTC is the fraud. That being said, re brands also happen, isn't it still soon enough to introduce the green color? I confess I'm undecided, but at first I don't see why the green couldn't work at some level, and yeah, it does look and feel better, merrier.

**Comment by bitsko** [comment]
Parkinson's Law of Triviality in action here.

**Comment by NxtChg** [comment]
> Parkinson's Law of Triviality in action here.

Branding is _not_ trivial. Especially if we target regular people outside the small cryptogeek community.

**Comment by t4t5** [comment]
I agree that branding is not trivial, especially in this case where there is a high risk of confusion between BTC and BCH.

Some recent developments from companies implementing Bitcoin Cash in their wallets seem to support my thesis that the green colour is a great way to differentiate from BTC.

BitPay:
bch-1

Bitcoin.com:
screen shot 2017-12-17 at 12 10 37

I think that trying to fight against it at this point is counter-productive.

**Comment by NxtChg** [comment]
@t4t5 Note that in the second picture they used small _orange_ icon, which just highlights how confusing it is to have the same color. It would be much better if the small icon was also green.

**Comment by singularity87** [comment]
@t4t5 We (Bitcoin Cash Fund) would love to use your original green site. Come and speak to us at https://chat.thebitcoincash.fund/ so we can discuss this further.

**Comment by coinfeller** [comment]
Hello,

I'm a noob and first I wanted to thank you all for what you for Bitcoin Cash! I discovered github when I translated the site into French.

Concerning the logo and the colours, it seems like businesses use the green logo because it helps to clearly differentiate with Bitcoin Core. I like the orange though but if it helps businesses like Coinbase or Bitcoin.com, that I use regularly, and if it also helps market adoption, I don't see the point of fighting for orange for Bitcoincash.org. Am I wrong?

**Comment by NxtChg** [comment]
https://medium.com/marketing-and-entrepreneurship/12-secrets-about-the-human-brain-that-will-make-you-a-better-marketer-e60d58b4240b

> Emotions process input 5 times faster than the conscious brain.

> Emotions make a more lasting imprint than rational thought.

> 62-90% of our feeling about a product is determined by the color alone

> Yellow activates the anxiety center of the brain.

**Comment by kingvest** [comment]
Go with the **GREEN** version

Make it a single page with scrolling

It's perfect design and was much needed to improve the current page

The first time I saw the current (old) bitcoincash website I thought it's a scam because the design looked so "cheap"

Now that I understand the true nature of BCH I want the website to reflect this as well ..

@t4t5 - You've made tremendous work (green version) and we should get this merged as soon as possible

**Comment by maplesyrupsucker** [comment]
Just wanted join in on the subjective opinions. I whipped up an alternative logomark. From a UI perspective most crypto apps / wallets / trading platforms use a square canvas. Our cash shaped rectangle causes BCH to look a bit wonky. We can't square the cash shape, because dollar-dollar-bills have never been square as far as I know. So what if we lean into the digital cash aspect of the name, by tying in the round shape from the old days, with the QR shape of tomorrow. Shows how the product works to some degree right in the design. And might solve the UI problem on crypto apps / wallets / trading platforms.

bitcoin-cash-qr-logo

I'm sharing orange only at the moment because I prefer orange. But I have a green variation around here too if anyone is hyper keen to see it.

**Comment by starvin** [comment]
Do you have a link to the original green demo? The entire Bitcoin Cash community has gravitated towards a green logo. I think it's time to revisit a green website redesign and this would be perfect.

**Comment by tofubear** [comment]
@starvin I'm cautious about changing colors at this point. Given more time, the market will lean toward the best logo. If the majority of projects, wallets, exchanges, etc are using the same color we will know which is best for the org website. That being said, maybe those entities are not aware of the multiple logo colors/choices that exist? Would there be value in having a small logo album or package that contains the community's best logos and make them available in one place?

**Comment by deadalnix** [comment]
@maplesyrupsucker would you be willing to A/B test that logo ?

**Pull request closed without merging**
